version: '3.8'

services:
  db:
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    restart: always
    environment:
      - ENVIRONMENT=production
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-change-this-in-production}
      - CORS_ORIGINS=${CORS_ORIGINS:-["http://localhost", "https://yourdomain.com"]}
      - CORREIOS_API_URL=${CORREIOS_API_URL:-https://api.correios.com.br}
      - CORREIOS_API_KEY=${CORREIOS_API_KEY:-change-this-in-production}
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    restart: always
    environment:
      - REACT_APP_API_URL=${API_URL:-http://localhost:8000}
      - REACT_APP_MOCK_API=false
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data:
